# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "basecode" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - run: npm i
      working-directory: '/home/ubuntu/actions-runner/_work/nodedemo/nodedemo/backend'
    - run: npm ci
      working-directory: '/home/ubuntu/actions-runner/_work/nodedemo/nodedemo/backend'
    - run: npm run build --if-present
      working-directory: '/home/ubuntu/actions-runner/_work/nodedemo/nodedemo/backend'
    - run: pm2 restart app.js
      working-directory: '/home/ubuntu/actions-runner/_work/nodedemo/nodedemo/backend'
